
export const SEARCH="SEARCH"
export const CART="CART"
export const FETCH_DATA_REQ="FETCH_DATA-REQ"
export const FETCH_DATA_SUCCESS="FETCH_DATA-SUCCESS"
export const FETCH_DATA_FAIL="FETCH_DATA-FAIL"
export const FETCH_SLIDER_DATA="FETCH_SLIDER_DATA"
export const FETCH_LINK_DATA="FETCH_LINK_DATA"
export const MODAL_TOGGLE="MODALTOGGLE"
export const CLOSE_TOGGLE="CLOSETOGGLE"
export const LOGOUT="LOGOUT"

